CrudFace/config/routes.rb
CrudFace::Engine.routes.draw do
  root to: 'index#index'

  get '/search', to: 'topics#search'
  resources :topics

end

CrudFace/app/models/crud_face/application_record.rb
module CrudFace
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

CrudFace/app/controllers/crud_face/application_controller.rb
module CrudFace
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

CrudFace/app/controllers/crud_face/index_controller.rb
module CrudFace
  class IndexController < CrudFace::ApplicationController

  end
end

CrudFace/app/controllers/crud_face/topics_controller.rb
module CrudFace
  class TopicsController < CrudFace::ApplicationController

    def search
      @results = CrudData::Topic.where("name LIKE :query", query: "%#{params['q']}%")
    end

    def create
      @topic = CrudData::Topic.new(topic_params)
      @topic.save
    end

    def update
      topic.update(topic_params)
    end

    def destroy
      topic.destroy
      respond_to do |format|
        format.html { redirect_to topics_url, notice: 'topic was successfully destroyed.' }
      end
    end

    private

    def topic
      @topic ||= CrudData::Topic.find(params[:id])
    end
    helper_method :topic

    def topic_params
      params.fetch(:topic, {}).permit(:name, :kind)
    end

  end
end

CrudFace/app/helpers/crud_face/application_helper.rb
module CrudFace
  module ApplicationHelper
  end
end

CrudFace/app/views/crud_face/crud_data/topics/_topic.html.haml
%li
  = link_to(topic.name, edit_topic_path(topic), remote: true)

CrudFace/app/views/crud_face/index/index.html.haml
= form_tag({controller: "topics", action: "search"}, method: "get", class: "topic_search_form", remote: true) do
  = label_tag(:q, "Search for:")
  = text_field_tag(:q, '', {class: "search_field"})
= form_for(CrudData::Topic.new, remote: true) do |f|
  = f.text_field :name, hidden: true
  = f.text_field :kind, hidden: true
  = f.submit


%ul.search.results

:javascript
  $('#q.search_field').keyup(function() {
    $('.topic_search_form').submit();
    $('#topic_name').val($(this).val());
  });

CrudFace/app/views/crud_face/topics/create.js.haml
:plain
  $.get( "#{request.original_url}/#{@topic.id}/edit", function( data ) {
    document.open();
    document.write(data);
    document.close();
  });

CrudFace/app/views/crud_face/topics/edit.html.haml
= form_for(topic, remote: true) do |f|
  Name:
  = f.text_field :name
  Kind:
  = f.text_field :kind
  = f.submit

CrudFace/app/views/crud_face/topics/edit.js.haml
:plain
  $.get( "#{request.original_url}", function( data ) {
    document.open();
    document.write(data);
    document.close();
  });

CrudFace/app/views/crud_face/topics/search.js.haml
$('.search.results li').each(function(index) {
$(this).fadeOut(300, function() { $(this).remove(); });
});
- @results.each do |result|
  $('.search.results').prepend("#{ escape_javascript(render result) }");

CrudFace/app/views/crud_face/topics/update.js.haml
$.get( "/", function( data ) {
document.open();
document.write(data);
document.close();
});

CrudFace/app/views/layouts/crud_face/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud face</title>
  <%= stylesheet_link_tag    "crud_face/application", media: "all" %>
  <%= javascript_include_tag "crud_face/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>